#!/bin/sh -e

case "$1" in
    purge)
        rm -rf /etc/puppetdb/conf.d
        rm -rf /usr/share/puppetdb /usr/share/puppetdb
        # Remove puppet log files
        rm -rf /var/log/puppetdb
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)


        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
